version: '3'
services: 
  collector:
    build: ./collector
    container_name: collector
    restart: always
    volumes: 
      - data:/var/log/
    ports: 
      - "514:514/tcp"
  transfo:
    build: ./transfo
    container_name: transfo
    restart: always
    depends_on: 
      - collector
      - db
    volumes: 
      - data:/data
  db:
    build: ./db
    container_name: db
    restart: always
  web:
    build: ./web
    container_name: web
    depends_on: 
      - transfo
    command: npm start
    volumes: 
      - ./web/:/web
      - data:/var/log/
    ports:
      - 80:3000
    environment:
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=admin
      - DOMAIN_NAME=example.com

volumes: 
  data:
