version: '3'
services: 
  collector:
    build: ./collector
    container_name: collector
    ports: 
      - "514:514/tcp"
      - "514:514/udp"
    volumes: 
      - ./collector/rsyslog.conf:/etc/rsyslog.conf
      - ./collector/data:/var/log
  db:
    build: ./db
    container_name: db
    restart: always
    ports: 
      - "38080:8080"
  app:
    build: ./app
    container_name: app
    volumes: 
      - ./app/:/app
    command: npm start
    ports:
    - 80:3000