version: '3'
services: 
  collector:
    build: ./collector
    container_name: collector
    restart: always
    ports:
      - "3522:22"
  db:
    build: ./db
    container_name: db
    restart: always
    ports: 
      - "38080:8080"
  app:
    build: ./app
    container_name: app
    volumes: 
      - ./app/:/app
    command: npm start
    ports:
    - 80:3000