version: '3'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    build: ./ovpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
  syslogserver:
    build: ./rsyslog
    hostname: syslog
    container_name: syslog
    restart: always
    volumes:
      - "./log:/var/log"
    cap_add:
      - SYSLOG
  db:
    image: rethinkdb:latest
    ports:
      - "38080:8080"
  web:
    image: node:alpine
    volumes: 
      - ./startup:/usr/startup
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NPM_PROXY_CACHE=${MINIENV_PROXY_CACHE}
    command: /usr/startup/startup.sh
    ports:
      - "33000:3000"
    depends_on:
      - db
