version: '3'
services: 
  collector:
    build: ./collector
    container_name: collector
    restart: always
    volumes: 
      - ./collector/rsyslog.conf:/etc/rsyslog.conf
      - data:/var/log
    ports: 
      - "514:514/tcp"
      - "514:514/udp"
  transfo:
    build: ./transfo
    container_name: transfo
    restart: always
    volumes: 
      - data:/data
  db:
    build: ./db
    container_name: db
    restart: always
    ports: 
      - "38080:8080"
  app:
    build: ./app
    container_name: app
    volumes: 
      - ./app/:/app
    command: npm start
    ports:
    - 80:3000

volumes: 
  data: