#!/bin/bash
read -p $'\e[31mCommon Name\e[0m: ' cn
cat > /templates/analog-client.template << EOF
cn=$cn
dns_name=$cn.local
tls_www_client
tls_www_server
EOF

cat > /templates/ca-analog-client.template << EOF
expiration_days=3650
tls_www_client
tls_www_server
dns_name=$cn.local
EOF

certtool --generate-privkey --outfile /opt/CA/analog-client.pem --sec-param High &>/dev/null
certtool --generate-request --load-privkey /opt/CA/analog-client.pem --outfile /opt/CA/analog-client.csr --template=/templates/analog-client.template &>/dev/null
certtool --generate-certificate --load-request /opt/CA/analog-client.csr --outfile /opt/CA/analog-client.crt --load-ca-certificate /opt/CA/ca.pem --load-ca-privkey /opt/CA/ca-key.pem --template=/templates/ca-analog-client.template &>/dev/null

echo -e "\033[33;1m[!] To send the certificate, you must enter your IP address and username to the Analog client\033[0m"
read -p $'\e[31mIP address\e[0m: ' ipaddress
read -p $'\e[31mUsername\e[0m: ' username

echo -e "\033[33;1m[!] Make sure you have created the /etc/rsyslog-tls folder and that you have write permission to send the certificates\033[0m"
rsync -aP /opt/CA/analog-client.* $username@$ipaddress:/etc/rsyslog-tls/
rsync -aP /opt/CA/ca.pem $username@$ipaddress:/etc/rsyslog-tls/
